# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - fs-modernize

stages:
  - stage: Lint
    jobs:
      - job: LinuxLint
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo "linted succesfully"
        displayName: 'Linting'
  - stage: CollectArtifacts
    dependsOn: Lint
    jobs:
      - job: CheckGitAnnex
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: none
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)'
        displayName: 'Check Cached Git Annex Data'
      - job: DownloadGitAnnex
        dependsOn: CheckGitAnnex
        condition: failed()
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - bash: ./ci-scripts/cache.git.annex.sh
            env:
              CURRENT_WORK_DIR: $(Agent.BuildDirectory)
          - publish: $(Agent.BuildDirectory)/annex-cache
            artifact: GitAnnex
        displayName: 'Download and Cache Git Annex Data'
  - stage: Build
    dependsOn: CollectArtifacts
    condition: succeededOrFailed()
    jobs:
      - job: XenialBuildGCC
        variables:
          HOSTING_OS: xenial
          HOSTING_COMPILER: gcc
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)/GitAnnex'
          - download: current
            artifact: 'GitAnnex'
            condition: failed()
          - script: ls
          - checkout: self
            submodules: true
          - script: |
              git remote add cache ../GitAnnex
              sudo apt-get install -y git-annex
              git config --global user.email "ahmed.s.aboualiaa@gmail.com"
              git config --global user.name "Ahmed Abou-Aliaa"
              git annex copy --from cache
              ./ci-scripts/travis.configure.${HOSTING_OS}.${HOSTING_COMPILER}.Build.sh
              ./ci-scripts/travis.script.${HOSTING_OS}.Build.sh
              git annex drop --force
              ./ci-scripts/travis.script.${HOSTING_OS}.Unit.sh
            displayName: 'Build and Test'
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '**/Test.xml'
              testRunTitle: 'cTest-$(HOSTING_OS)-$(HOSTING_COMPILER)-UnitTests'
        displayName: 'Ubuntu Xenial Build GCC'
      - job: XenialBuildClang
        variables:
          HOSTING_OS: xenial
          HOSTING_COMPILER: clang
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)/GitAnnex'
          - download: current
            artifact: 'GitAnnex'
            condition: failed()
          - checkout: self
            submodules: true
          - script: |
              git remote add cache ../GitAnnex
              sudo apt-get install -y git-annex
              git config --global user.email "ahmed.s.aboualiaa@gmail.com"
              git config --global user.name "Ahmed Abou-Aliaa"
              git annex copy --from cache
              ./ci-scripts/travis.configure.${HOSTING_OS}.${HOSTING_COMPILER}.Build.sh
              ./ci-scripts/travis.script.${HOSTING_OS}.Build.sh
              git annex drop --force
              ./ci-scripts/travis.script.${HOSTING_OS}.Unit.sh
            displayName: 'Build and Test'
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '**/Test.xml'
              testRunTitle: 'cTest-$(HOSTING_OS)-$(HOSTING_COMPILER)-UnitTests'
        displayName: 'Ubuntu Xenial Build Clang'
      - job: BionicBuildGCC
        variables:
          HOSTING_OS: bionic
          HOSTING_COMPILER: gcc
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)/GitAnnex'
          - download: current
            artifact: 'GitAnnex'
            condition: failed()
          - checkout: self
            submodules: true
          - script: |
              git remote add cache ../GitAnnex
              sudo apt-get install -y git-annex
              git config --global user.email "ahmed.s.aboualiaa@gmail.com"
              git config --global user.name "Ahmed Abou-Aliaa"
              git annex copy --from cache
              ./ci-scripts/travis.configure.${HOSTING_OS}.${HOSTING_COMPILER}.Build.sh
              ./ci-scripts/travis.script.${HOSTING_OS}.Build.sh
              git annex drop --force
              ./ci-scripts/travis.script.${HOSTING_OS}.Unit.sh
            displayName: 'Build and Test'
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '**/Test.xml'
              testRunTitle: 'cTest-$(HOSTING_OS)-$(HOSTING_COMPILER)-UnitTests'
        displayName: 'Ubuntu Bionic Build GCC'
      - job: BionicBuildClang
        variables:
          HOSTING_OS: bionic
          HOSTING_COMPILER: clang
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)/GitAnnex'
          - download: current
            artifact: 'GitAnnex'
            condition: failed()
          - checkout: self
            submodules: true
          - script: |
              git remote add cache ../GitAnnex
              sudo apt-get install -y git-annex
              git config --global user.email "ahmed.s.aboualiaa@gmail.com"
              git config --global user.name "Ahmed Abou-Aliaa"
              git annex copy --from cache
              ./ci-scripts/travis.configure.${HOSTING_OS}.${HOSTING_COMPILER}.Build.sh
              ./ci-scripts/travis.script.${HOSTING_OS}.Build.sh
              git annex drop --force
              ./ci-scripts/travis.script.${HOSTING_OS}.Unit.sh
            displayName: 'Build and Test'
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '**/Test.xml'
              testRunTitle: 'cTest-$(HOSTING_OS)-$(HOSTING_COMPILER)-UnitTests'
        displayName: 'Ubuntu Bionic Build Clang'
      - job: XenialIntegrationTestGCC
        timeoutInMinutes: 300
        variables:
          HOSTING_OS: xenial
          HOSTING_COMPILER: gcc
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)/GitAnnex'
          - download: current
            artifact: 'GitAnnex'
            condition: failed()
          - checkout: self
            submodules: true
          - script: |
              git remote add cache ../GitAnnex
              sudo apt-get install -y git-annex
              git config --global user.email "ahmed.s.aboualiaa@gmail.com"
              git config --global user.name "Ahmed Abou-Aliaa"
              git annex copy --from cache
              ./ci-scripts/travis.configure.${HOSTING_OS}.${HOSTING_COMPILER}.Build.sh
              ./ci-scripts/travis.script.${HOSTING_OS}.Build.sh
              git annex drop --force
              ./ci-scripts/travis.script.${HOSTING_OS}.Integration.sh
            displayName: 'Build and Test'
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '**/Test.xml'
              testRunTitle: 'cTest-$(HOSTING_OS)-$(HOSTING_COMPILER)-IntegrationTests'
        displayName: 'Ubuntu Xenial Integration Test GCC'
      - job: XenialIntegrationTestClang
        timeoutInMinutes: 300
        variables:
          HOSTING_OS: xenial
          HOSTING_COMPILER: clang
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)/GitAnnex'
          - download: current
            artifact: 'GitAnnex'
            condition: failed()
          - checkout: self
            submodules: true
          - script: |
              git remote add cache ../GitAnnex
              sudo apt-get install -y git-annex
              git config --global user.email "ahmed.s.aboualiaa@gmail.com"
              git config --global user.name "Ahmed Abou-Aliaa"
              git annex copy --from cache
              ./ci-scripts/travis.configure.${HOSTING_OS}.${HOSTING_COMPILER}.Build.sh
              ./ci-scripts/travis.script.${HOSTING_OS}.Build.sh
              git annex drop --force
              ./ci-scripts/travis.script.${HOSTING_OS}.Integration.sh
            displayName: 'Build and Test'
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '**/Test.xml'
              testRunTitle: 'cTest-$(HOSTING_OS)-$(HOSTING_COMPILER)-IntegrationTests'
        displayName: 'Ubuntu Xenial Integration Test Clang'
      - job: BionicIntegrationTestGCC
        timeoutInMinutes: 300
        variables:
          HOSTING_OS: bionic
          HOSTING_COMPILER: gcc
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)/GitAnnex'
          - download: current
            artifact: 'GitAnnex'
            condition: failed()
          - checkout: self
            submodules: true
          - script: |
              git remote add cache ../GitAnnex
              sudo apt-get install -y git-annex
              git config --global user.email "ahmed.s.aboualiaa@gmail.com"
              git config --global user.name "Ahmed Abou-Aliaa"
              git annex copy --from cache
              ./ci-scripts/travis.configure.${HOSTING_OS}.${HOSTING_COMPILER}.Build.sh
              ./ci-scripts/travis.script.${HOSTING_OS}.Build.sh
              git annex drop --force
              ./ci-scripts/travis.script.${HOSTING_OS}.Integration.sh
            displayName: 'Build and Test'
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '**/Test.xml'
              testRunTitle: 'cTest-$(HOSTING_OS)-$(HOSTING_COMPILER)-IntegrationTests'
        displayName: 'Ubuntu Bionic Integration Test GCC'
      - job: BionicIntegrationTestClang
        timeoutInMinutes: 300
        variables:
          HOSTING_OS: bionic
          HOSTING_COMPILER: clang
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)/GitAnnex'
          - download: current
            artifact: 'GitAnnex'
            condition: failed()
          - checkout: self
            submodules: true
          - script: |
              git remote add cache ../GitAnnex
              sudo apt-get install -y git-annex
              git config --global user.email "ahmed.s.aboualiaa@gmail.com"
              git config --global user.name "Ahmed Abou-Aliaa"
              git annex copy --from cache
              ./ci-scripts/travis.configure.${HOSTING_OS}.${HOSTING_COMPILER}.Build.sh
              ./ci-scripts/travis.script.${HOSTING_OS}.Build.sh
              git annex drop --force
            displayName: 'Build and Test'
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Integration.sh
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '**/Test.xml'
              testRunTitle: 'cTest-$(HOSTING_OS)-$(HOSTING_COMPILER)-IntegrationTests'
        displayName: 'Ubuntu Bionic Integration Test Clang'
