git:
  depth: 1
  quiet: true

language: cpp

jobs:
  include:
    - os: osx
      env:
        - HOSTING_OS=osx
        - PATH="/usr/local/opt/python/libexec/bin:$PATH"
        - PATH="/usr/local/opt/llvm/bin:$PATH"
      osx_image: xcode11.3
      addons:
        homebrew:
          update: true
          packages:
            - itk
            - vtk
            - petsc
            - cmake
            - python@3
            - gcc@9
            - jemalloc
            - tcsh
            - armadillo
            - qt
            - hdf5
            - libomp
            - szip
            - fltk
            - open-mpi
            - eigen
            - ninja
      cache:
        directories:
          - packages/hpx
          - cmake-build-release
    - os: linux
      env: HOSTING_OS=trusty
      dist: trusty
      addons:
        apt:
          packages:
            - gfortran
            - libxi-dev
            - liblapack-dev
            - python3.5-dev
            - tcsh
            - curl
            - git
            - cmake
      cache:
        - apt
        - ccache
    - os: linux
      env: HOSTING_OS=xenial
      dist: xenial
      addons:
        apt:
          packages:
            - gfortran
            - libxi-dev
            - liblapack-dev
            - python3.5-dev
            - tcsh
            - curl
            - git
            - cmake
      cache:
        - apt
        - ccache
    - os: linux
      env: HOSTING_OS=bionic
      dist: bionic
      addons:
        apt:
          packages:
            - gfortran
            - libxi-dev
            - liblapack-dev
            - python3.6-dev
            - tcsh
            - curl
            - git
            - cmake
      cache:
        - apt
        - ccache

before_install:
  - ./ci-scripts/travis.configure.${HOSTING_OS}.sh

script:
  - ./ci-scripts/travis.script.${HOSTING_OS}.sh

#before_install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get -q update
#  - sudo apt-get -y install gcc-9
#  - sudo apt-get -y install gfortran-9
#  - sudo apt-get -y install cmake
#  - sudo apt-get -y install python3.7-dev
#  - sudo apt-get -y install libxi-dev
#  - sudo apt-get -y install liblapack-dev
#  - sudo apt-get -y install tcsh
#  - sudo apt-get -y install curl
#  - sudo apt-get -y install git
#  - sudo apt-get -y install libx11-dev

