#os: linux
#dist: bionic

#cache:
#  - apt
#  - ccache

git:
  depth: false
  quiet: true

language: cpp

jobs:
  include:
    - os: osx
      osx_image: xcode11.3
      addons:
        homebrew:
          packages:
            - itk
            - vtk
            - petsc
            - cmake
            - python@3
            - gcc@9
            - jemalloc
            - tcsh
            - armadillo
            - qt
            - hdf5
            - libomp
            - szip
            - fltk
            - open-mpi
            - eigen
      cache:
        directories:
          - packages/hpx
          - cmake-build-release

before_install:
  - alias python='python3'
  - export PATH="/usr/local/opt/python/libexec/bin:$PATH"
  - ./ci-scripts/install-ninja.sh
  - ./ci-scripts/restore-mtime.sh
  - ./ci-scripts/install-hpx.sh

script:
  - sudo xcode-select -r # s /Applications/Xcode.app
  - mkdir -p cmake-build-release && cd ./cmake-build-release
  - rm ./CMakeCache.txt # remove cache in case travis updated xcode
  - cmake -G Ninja -DGEMS_BUILD_MATLAB=OFF ..
  - cmake -G Ninja -DGEMS_BUILD_MATLAB=OFF .. # again so that appleclang finds openMP
  - timeout 30m ninja

# os: linux
#      addons:
#        apt:
#          packages:
#            #            - gfortran
#            - git
#
#before_install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get -q update
#  - sudo apt-get -y install gcc-9
#  - sudo apt-get -y install gfortran-9
#  - sudo apt-get -y install cmake
#  - sudo apt-get -y install python3.7-dev
#  - sudo apt-get -y install libxi-dev
#  - sudo apt-get -y install liblapack-dev
#  - sudo apt-get -y install tcsh
#  - sudo apt-get -y install curl
#  #  - sudo apt-get -y install git
#  - sudo apt-get -y install libx11-dev

#install:
#  - curl --connect-timeout 8 --retry 5 -O http://surfer.nmr.mgh.harvard.edu/pub/data/fspackages/prebuilt/centos7-packages.tar.gz
#  - tar -xzf centos7-packages.tar.gz
#
#script:
#  - cmake . -DFS_PACKAGES_DIR=packages -DBUILD_GUIS=OFF && make -j4
