os: linux
dist: bionic
language: cpp

cache:
  - apt
  - ccache

jobs:
  include:
    - os: linux
      addons:
        apt:
          packages:
            #            - gfortran
            - git

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install gcc-9
  - sudo apt-get -y install gfortran-9
  - sudo apt-get -y install cmake
  - sudo apt-get -y install python3.7-dev
  - sudo apt-get -y install libxi-dev
  - sudo apt-get -y install liblapack-dev
  - sudo apt-get -y install tcsh
  - sudo apt-get -y install curl
  #  - sudo apt-get -y install git
  - sudo apt-get -y install libx11-dev

install:
  - curl --connect-timeout 8 --retry 5 -O http://surfer.nmr.mgh.harvard.edu/pub/data/fspackages/prebuilt/centos7-packages.tar.gz
  - tar -xzf centos7-packages.tar.gz

script:
  - cmake . -DFS_PACKAGES_DIR=packages -DBUILD_GUIS=OFF && make -j4
