git:
  depth: 1
  quiet: true

language: cpp

jobs:
  include:
    - os: osx
      env:
        - ON_OSX=true
        - PATH="/usr/local/opt/python/libexec/bin:$PATH"
        - PATH="/usr/local/opt/llvm/bin:$PATH"
      osx_image: xcode11.3
      addons:
        homebrew:
          packages:
            - itk
            - vtk
            - petsc
            - cmake
            - python@3
            - gcc@9
            - jemalloc
            - tcsh
            - armadillo
            - qt
            - hdf5
            - libomp
            - szip
            - fltk
            - open-mpi
            - eigen
      cache:
        directories:
          - packages/hpx
          - cmake-build-release
    - os: linux
      env: ON_LINUX=true
      dist: trusty
      addons:
        apt:
          packages:
            - gfortran
            - libxi-dev
            - liblapack-dev
            - python3.5-dev
            - tcsh
            - curl
            - git
            - cmake
      cache:
        - apt
        - ccache

before_install:
  - if [[ $ON_OSX ]]; then ./ci-scripts/before_install_osx.sh; fi
  - if [[ $ON_LINUX ]]; then ./ci-scripts/before_install_linux.sh; fi

script:
  - if [[ $ON_OSX ]]; then ./ci-scripts/script_osx.sh; fi
  - if [[ $ON_LINUX ]]; then ./ci-scripts/script_linux.sh; fi

#before_install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get -q update
#  - sudo apt-get -y install gcc-9
#  - sudo apt-get -y install gfortran-9
#  - sudo apt-get -y install cmake
#  - sudo apt-get -y install python3.7-dev
#  - sudo apt-get -y install libxi-dev
#  - sudo apt-get -y install liblapack-dev
#  - sudo apt-get -y install tcsh
#  - sudo apt-get -y install curl
#  - sudo apt-get -y install git
#  - sudo apt-get -y install libx11-dev

