# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Freesurfer.Linux

trigger:
  branches:
    include:
      - fs-modernize

stages:
  - stage: Lint
    jobs:
      - job: LinuxLint
        variables:
          Z_ID: $(System.DefinitionId)
          B_ID: $(Build.BuildId)
          BUILDDIR: $(Agent.BuildDirectory)
          PIPEDIR: $(Pipeline.Workspace)
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo "linted succesfully"
          - script: echo $B_ID
          - script: echo $Z_ID
          - script: echo $BUILDDIR
          - script: echo $PIPEDIR
        displayName: 'Linting'
  - stage: CollectArtifacts
    dependsOn: Lint
    jobs:
      - job: CheckGitAnnex
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: cd .. && pwd && ls
          - checkout: none
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)'
          - script: cd .. && pwd && ls
        displayName: 'Check Cached Git Annex Data'
      - job: DownloadGitAnnex
        dependsOn: CheckGitAnnex
        condition: failed()
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - bash: ./ci-scripts/cache.git.annex.sh
            env:
              CURRENT_WORK_DIR: $(Agent.BuildDirectory)
          - publish: $(Agent.BuildDirectory)/annex-cache
            artifact: GitAnnex
        displayName: 'Download and Cache Git Annex Data'
  - stage: Build
    dependsOn: CollectArtifacts
    condition: succeededOrFailed()
    jobs:
      - job: XenialBuildGCC
        variables:
          HOSTING_OS: xenial
          HOSTING_COMPILER: gcc
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: cd .. && pwd && ls
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)/GitAnnex'
          - download: current
            artifact: 'GitAnnex'
            condition: failed()
          - script: cd .. && pwd && ls
          - script: ls
          - checkout: self
            submodules: true
          - script: git remote add cache ../GitAnnex
          - script: sudo apt-get install -y git-annex
          - script: git config --global user.email "ahmed.s.aboualiaa@gmail.com"
          - script: git config --global user.name "Ahmed Abou-Aliaa"
          - script: git annex copy --from cache
          - script: ./ci-scripts/travis.configure.${HOSTING_OS}.${HOSTING_COMPILER}.Build.sh
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Build.sh
          - script: git annex drop --force
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Unit.sh
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '**/Test.xml'
        displayName: 'Ubuntu Xenial Build GCC'
      - job: XenialBuildClang
        variables:
          HOSTING_OS: xenial
          HOSTING_COMPILER: clang
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)/GitAnnex'
          - download: current
            artifact: 'GitAnnex'
            condition: failed()
          - checkout: self
            submodules: true
          - script: git remote add cache ../GitAnnex
          - script: sudo apt-get install -y git-annex
          - script: git config --global user.email "ahmed.s.aboualiaa@gmail.com"
          - script: git config --global user.name "Ahmed Abou-Aliaa"
          - script: git annex copy --from cache
          - script: ./ci-scripts/travis.configure.${HOSTING_OS}.${HOSTING_COMPILER}.Build.sh
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Build.sh
          - script: git annex drop --force
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Unit.sh
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '**/Test.xml'
        displayName: 'Ubuntu Xenial Build Clang'
      - job: BionicBuildGCC
        variables:
          HOSTING_OS: bionic
          HOSTING_COMPILER: gcc
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)/GitAnnex'
          - download: current
            artifact: 'GitAnnex'
            condition: failed()
          - checkout: self
            submodules: true
          - script: git remote add cache ../GitAnnex
          - script: sudo apt-get install -y git-annex
          - script: git config --global user.email "ahmed.s.aboualiaa@gmail.com"
          - script: git config --global user.name "Ahmed Abou-Aliaa"
          - script: git annex copy --from cache
          - script: ./ci-scripts/travis.configure.${HOSTING_OS}.${HOSTING_COMPILER}.Build.sh
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Build.sh
          - script: git annex drop --force
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Unit.sh
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '**/Test.xml'
        displayName: 'Ubuntu Bionic Build GCC'
      - job: BionicBuildClang
        variables:
          HOSTING_OS: bionic
          HOSTING_COMPILER: clang
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)/GitAnnex'
          - download: current
            artifact: 'GitAnnex'
            condition: failed()
          - checkout: self
            submodules: true
          - script: git remote add cache ../GitAnnex
          - script: sudo apt-get install -y git-annex
          - script: git config --global user.email "ahmed.s.aboualiaa@gmail.com"
          - script: git config --global user.name "Ahmed Abou-Aliaa"
          - script: git annex copy --from cache
          - script: ./ci-scripts/travis.configure.${HOSTING_OS}.${HOSTING_COMPILER}.Build.sh
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Build.sh
          - script: git annex drop --force
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Unit.sh
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '**/Test.xml'
        displayName: 'Ubuntu Bionic Build Clang'
      - job: XenialIntegrationTestGCC
        timeoutInMinutes: 300
        variables:
          HOSTING_OS: xenial
          HOSTING_COMPILER: gcc
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)/GitAnnex'
          - download: current
            artifact: 'GitAnnex'
            condition: failed()
          - checkout: self
            submodules: true
          - script: git remote add cache ../GitAnnex
          - script: sudo apt-get install -y git-annex
          - script: git config --global user.email "ahmed.s.aboualiaa@gmail.com"
          - script: git config --global user.name "Ahmed Abou-Aliaa"
          - script: git annex copy --from cache
          - script: ./ci-scripts/travis.configure.${HOSTING_OS}.${HOSTING_COMPILER}.Build.sh
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Build.sh
          - script: git annex drop --force
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Integration.sh
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '**/Test.xml'
        displayName: 'Ubuntu Xenial Integration Test GCC'
      - job: XenialIntegrationTestClang
        timeoutInMinutes: 300
        variables:
          HOSTING_OS: xenial
          HOSTING_COMPILER: clang
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)/GitAnnex'
          - download: current
            artifact: 'GitAnnex'
            condition: failed()
          - checkout: self
            submodules: true
          - script: git remote add cache ../GitAnnex
          - script: sudo apt-get install -y git-annex
          - script: git config --global user.email "ahmed.s.aboualiaa@gmail.com"
          - script: git config --global user.name "Ahmed Abou-Aliaa"
          - script: git annex copy --from cache
          - script: ./ci-scripts/travis.configure.${HOSTING_OS}.${HOSTING_COMPILER}.Build.sh
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Build.sh
          - script: git annex drop --force
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Integration.sh
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '**/Test.xml'
        displayName: 'Ubuntu Xenial Integration Test Clang'
      - job: BionicIntegrationTestGCC
        timeoutInMinutes: 300
          variables:
            HOSTING_OS: bionic
            HOSTING_COMPILER: gcc
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)/GitAnnex'
          - download: current
            artifact: 'GitAnnex'
            condition: failed()
          - checkout: self
            submodules: true
          - script: git remote add cache ../GitAnnex
          - script: sudo apt-get install -y git-annex
          - script: git config --global user.email "ahmed.s.aboualiaa@gmail.com"
          - script: git config --global user.name "Ahmed Abou-Aliaa"
          - script: git annex copy --from cache
          - script: ./ci-scripts/travis.configure.${HOSTING_OS}.${HOSTING_COMPILER}.Build.sh
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Build.sh
          - script: git annex drop --force
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Integration.sh
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '**/Test.xml'
        displayName: 'Ubuntu Bionic Integration Test GCC'
      - job: BionicIntegrationTestClang
        timeoutInMinutes: 300
          variables:
            HOSTING_OS: bionic
            HOSTING_COMPILER: clang
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1eee1365-4e03-49ce-a8e3-c84dd1212c9e'
              definition: '2'
              buildVersionToDownload: 'specific'
              pipelineId: '31'
              artifactName: 'GitAnnex'
              targetPath: '$(Agent.BuildDirectory)/GitAnnex'
          - download: current
            artifact: 'GitAnnex'
            condition: failed()
          - checkout: self
            submodules: true
          - script: git remote add cache ../GitAnnex
          - script: sudo apt-get install -y git-annex
          - script: git config --global user.email "ahmed.s.aboualiaa@gmail.com"
          - script: git config --global user.name "Ahmed Abou-Aliaa"
          - script: git annex copy --from cache
          - script: ./ci-scripts/travis.configure.${HOSTING_OS}.${HOSTING_COMPILER}.Build.sh
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Build.sh
          - script: git annex drop --force
          - script: ./ci-scripts/travis.script.${HOSTING_OS}.Integration.sh
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '**/Test.xml'
        displayName: 'Ubuntu Bionic Integration Test Clang'
